/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
/**
 *
 * @author Ananda Rafli
 */
public class FormMenu extends javax.swing.JFrame {
String idMenuTerpilih = "";
    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        tampilKategori();
        tampilkanData();
    }
    
    // Fungsi 1: Menampilkan daftar kategori dari tb_kategori ke ComboBox
private void tampilKategori() {
    try {
        Connection conn = Koneksi.configDB();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM tb_kategori");
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem("- Pilih Kategori -");
        
        while (rs.next()) {
            // Memasukkan nama kategori ke dalam dropdown
            jComboBox1.addItem(rs.getString("nama_kategori")); 
        }
    } catch (Exception e) {
        System.out.println("Error tampil kategori: " + e.getMessage());
    }
}

// Fungsi 2: Menampilkan daftar menu dari tb_menu ke JTable
private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("ID Menu");
    model.addColumn("Kategori"); 
    model.addColumn("Nama Menu");
    model.addColumn("Harga");
    model.addColumn("Stok");
    
    try {
        int no = 1;
        // Menggunakan teknik JOIN untuk menggabungkan tb_menu dan tb_kategori
        String sql = "SELECT m.id_menu, k.nama_kategori, m.nama_menu, m.harga, m.stok "
                   + "FROM tb_menu m JOIN tb_kategori k ON m.id_kategori = k.id_kategori";
        
        Connection conn = Koneksi.configDB();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        
        while (rs.next()) {
            model.addRow(new Object[]{
                no++, 
                rs.getString("id_menu"), 
                rs.getString("nama_kategori"), // Menampilkan nama, bukan ID
                rs.getString("nama_menu"), 
                rs.getString("harga"),
                rs.getString("stok")
            });
        }
        jTable1.setModel(model);
        
    } catch (Exception e) {
        System.out.println("Error tampil data menu: " + e.getMessage());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("FORM KELOLA MENU");

        jLabel2.setText("Kategori");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Nama Menu");

        jLabel4.setText("Harga");

        jLabel5.setText("Stok");

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jComboBox1, 0, 120, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
    String kategoriTerpilih = jComboBox1.getSelectedItem().toString();
    String namaMenu = jTextField1.getText();
    String harga = jTextField2.getText();
    String stok = jTextField3.getText();
    
    // Validasi form kosong
    if (kategoriTerpilih.equals("- Pilih Kategori -") || namaMenu.equals("") || harga.equals("") || stok.equals("")) {
        JOptionPane.showMessageDialog(null, "Semua data (Kategori, Nama Menu, Harga, Stok) wajib diisi!");
        return;
    }
    
    java.sql.Connection conn = Koneksi.configDB();
    java.sql.Statement st = conn.createStatement();
    
    // 1. Cari tau id_kategori dari nama yang dipilih di JComboBox
    String sqlCariKategori = "SELECT id_kategori FROM tb_kategori WHERE nama_kategori = '" + kategoriTerpilih + "'";
    java.sql.ResultSet rs = st.executeQuery(sqlCariKategori);
    
    String idKategori = "";
    if (rs.next()) {
        idKategori = rs.getString("id_kategori");
    }
    
    // 2. Simpan data ke tb_menu menggunakan id_kategori yang baru didapatkan
    String sqlInsert = "INSERT INTO tb_menu (id_kategori, nama_menu, harga, stok) VALUES ('" + idKategori + "', '" + namaMenu + "', '" + harga + "', '" + stok + "')";
    st.executeUpdate(sqlInsert);
    
    JOptionPane.showMessageDialog(null, "Data Menu Berhasil Disimpan!");
    tampilkanData(); // Refresh JTable
    
    // Memanggil aksi tombol reset secara otomatis setelah simpan
    jButton4.doClick(); // Mengasumsikan jButton4 adalah tombol Reset kamu
    
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error Simpan: " + e.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(0); // Mengembalikan dropdown ke "- Pilih Kategori -"
        jTextField1.setText(""); // Mengosongkan Nama Menu
        jTextField2.setText(""); // Mengosongkan Harga
        jTextField3.setText(""); // Mengosongkan Stok
        idMenuTerpilih = ""; // Mereset memori ID
        jTable1.clearSelection(); // Menghilangkan seleksi pada tabel
        jTextField1.requestFocus(); // Mengembalikan kursor
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();

        // Mengambil ID Menu untuk keperluan Edit/Hapus
        idMenuTerpilih = jTable1.getValueAt(baris, 1).toString(); 

        // Memasukkan data dari tabel kembali ke form input
        jComboBox1.setSelectedItem(jTable1.getValueAt(baris, 2).toString()); // Kategori
        jTextField1.setText(jTable1.getValueAt(baris, 3).toString()); // Nama Menu
        jTextField2.setText(jTable1.getValueAt(baris, 4).toString()); // Harga
        jTextField3.setText(jTable1.getValueAt(baris, 5).toString()); // Stok
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
    String kategoriTerpilih = jComboBox1.getSelectedItem().toString();
    String namaMenu = jTextField1.getText();
    String harga = jTextField2.getText();
    String stok = jTextField3.getText();
    
    if (idMenuTerpilih.equals("") || kategoriTerpilih.equals("- Pilih Kategori -") || namaMenu.equals("") || harga.equals("") || stok.equals("")) {
        JOptionPane.showMessageDialog(null, "Pilih data di tabel dan pastikan form tidak kosong!");
        return;
    }
    
    java.sql.Connection conn = Koneksi.configDB();
    java.sql.Statement st = conn.createStatement();
    
    // Cari id_kategori yang baru berdasarkan nama kategori di dropdown
    String sqlCariKategori = "SELECT id_kategori FROM tb_kategori WHERE nama_kategori = '" + kategoriTerpilih + "'";
    java.sql.ResultSet rs = st.executeQuery(sqlCariKategori);
    
    String idKategori = "";
    if (rs.next()) {
        idKategori = rs.getString("id_kategori");
    }
    
    // Eksekusi proses Update
    String sqlUpdate = "UPDATE tb_menu SET id_kategori = '" + idKategori + "', nama_menu = '" + namaMenu + "', harga = '" + harga + "', stok = '" + stok + "' WHERE id_menu = '" + idMenuTerpilih + "'";
    st.executeUpdate(sqlUpdate);
    
    JOptionPane.showMessageDialog(null, "Data Menu Berhasil Diubah!");
    tampilkanData(); // Refresh JTable
    jButton4.doClick(); // Panggil tombol Reset
    
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error Edit: " + e.getMessage());
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
    if (idMenuTerpilih.equals("")) {
        JOptionPane.showMessageDialog(null, "Silakan pilih data pada tabel yang ingin dihapus!");
        return;
    }
    
    int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus menu ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    
    if (konfirmasi == JOptionPane.YES_OPTION) {
        String sqlDelete = "DELETE FROM tb_menu WHERE id_menu = '" + idMenuTerpilih + "'";
        java.sql.Connection conn = Koneksi.configDB();
        java.sql.Statement st = conn.createStatement();
        st.executeUpdate(sqlDelete);
        
        JOptionPane.showMessageDialog(null, "Data Menu Berhasil Dihapus!");
        tampilkanData(); // Refresh JTable
        jButton4.doClick(); // Panggil tombol Reset
    }
    
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error Hapus: " + e.getMessage());
}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
