/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package transaksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat; // Untuk tanggal otomatis
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
/**
 *
 * @author Ananda Rafli
 */
public class FormTransaksi extends javax.swing.JFrame {
// Membuat model tabel keranjang yang kosong di awal
DefaultTableModel modelKeranjang;
int grandTotal = 0;

private void setupKeranjang() {
    modelKeranjang = new DefaultTableModel();
    modelKeranjang.addColumn("ID Menu");
    modelKeranjang.addColumn("Nama Menu");
    modelKeranjang.addColumn("Harga");
    modelKeranjang.addColumn("Qty");
    modelKeranjang.addColumn("Subtotal");
    
    jTable1.setModel(modelKeranjang);
}

private void hitungTotal() {
    grandTotal = 0;
    // Melakukan perulangan untuk membaca semua baris di tabel keranjang
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        // Mengambil nilai dari kolom index 4 (Subtotal)
        grandTotal += Integer.parseInt(jTable1.getValueAt(i, 4).toString());
    }
    // Menampilkan total ke Label besar yang kamu buat
    jLabelTotal.setText("Rp. " + grandTotal); 
}

    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi() {
        initComponents();
        setupKeranjang(); // Menyiapkan kolom keranjang
        tampilMenu(); // Memunculkan daftar produk jualan
    }

    private void tampilMenu() {
    try {
        Connection conn = Koneksi.configDB();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM tb_menu");
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem("- Pilih Menu -");
        
        while (rs.next()) {
            jComboBox1.addItem(rs.getString("nama_menu")); 
        }
    } catch (Exception e) {
        System.out.println("Error tampil menu: " + e.getMessage());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Input Pesanan");

        jLabel2.setText("Pilih Menu");

        jLabel3.setText("Harga");

        jLabel4.setText("Jumlah Beli");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Tambah ke Keranjang");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Keranjang Belanja");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Pembayaran");

        jLabelTotal.setText("Rp. 0");

        jLabel8.setText("Total");

        jLabel9.setText("Uang Tunai");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jLabel10.setText("Kembalian");

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Bayar dan Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, 0, 120, Short.MAX_VALUE)
                                .addComponent(jTextField1)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addGap(31, 31, 31))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(35, 35, 35)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTotal)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        try {
    if (jComboBox1.getSelectedItem() != null) {
        
        String namaMenu = jComboBox1.getSelectedItem().toString();
        
        if (!namaMenu.equals("- Pilih Menu -")) {
            java.sql.Connection conn = Koneksi.configDB();
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery("SELECT harga FROM tb_menu WHERE nama_menu = '" + namaMenu + "'");
            
            if (rs.next()) {
                jTextField1.setText(rs.getString("harga")); 
                jTextField1.setEditable(false); 
            }
        } else {
            jTextField1.setText(""); 
        }
        
    } // Akhir dari pengecekan null
    
} catch (Exception e) {
    System.out.println("Error tampil harga: " + e.getMessage());
}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
    String namaMenu = jComboBox1.getSelectedItem().toString();
    String harga = jTextField1.getText();
    String qty = jTextField2.getText();
    
    if (namaMenu.equals("- Pilih Menu -") || harga.equals("") || qty.equals("")) {
        JOptionPane.showMessageDialog(null, "Pilih menu dan masukkan jumlah beli (Qty)!");
        return;
    }
    
    // 1. Mencari id_menu dari database (dibutuhkan nanti untuk tabel detail_transaksi)
    String idMenu = "";
    java.sql.Connection conn = Koneksi.configDB();
    java.sql.Statement st = conn.createStatement();
    java.sql.ResultSet rs = st.executeQuery("SELECT id_menu FROM tb_menu WHERE nama_menu = '" + namaMenu + "'");
    if (rs.next()) {
        idMenu = rs.getString("id_menu");
    }
    
    // 2. Menghitung Subtotal (Harga x Qty)
    int subtotal = Integer.parseInt(harga) * Integer.parseInt(qty);
    
    // 3. Memasukkan data ke baris JTable (Keranjang)
    modelKeranjang.addRow(new Object[]{
        idMenu,
        namaMenu,
        harga,
        qty,
        String.valueOf(subtotal)
    });
    
    // 4. Update Grand Total
    hitungTotal();
    
    // 5. Bersihkan form input untuk pesanan berikutnya
    jComboBox1.setSelectedIndex(0);
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField2.requestFocus();
    
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error masuk keranjang: " + e.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
    // 1. Validasi keranjang dan pembayaran
    if (modelKeranjang.getRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "Keranjang masih kosong!");
        return;
    }
    
    int bayar = Integer.parseInt(jTextField3.getText());
    if (bayar < grandTotal) {
        JOptionPane.showMessageDialog(null, "Uang pembayaran kurang!");
        return;
    }
    
    Connection conn = Koneksi.configDB();
    
    // 2. Simpan ke tb_transaksi
    // Kita buat tanggal hari ini secara otomatis
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String tanggal = sdf.format(new Date());
    
    // Catatan: Untuk testing, kita asumsikan id_kasir = 1.
    String sqlTransaksi = "INSERT INTO tb_transaksi (id_kasir, tanggal_transaksi, total_bayar) VALUES ('2', '" + tanggal + "', '" + grandTotal + "')";
    
    // Statement khusus untuk mengambil ID transaksi yang baru saja digenerate oleh database
    Statement st = conn.createStatement();
    st.executeUpdate(sqlTransaksi, Statement.RETURN_GENERATED_KEYS);
    
    ResultSet rs = st.getGeneratedKeys();
    int idTransaksiBaru = 0;
    if (rs.next()) {
        idTransaksiBaru = rs.getInt(1); // Menyimpan ID transaksi baru (misal: Transaksi ke-15)
    }
    
    // 3. Simpan ke tb_detail_transaksi & Kurangi Stok secara berulang sebanyak isi keranjang
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        String idMenu = jTable1.getValueAt(i, 0).toString();
        String qty = jTable1.getValueAt(i, 3).toString();
        String subtotal = jTable1.getValueAt(i, 4).toString();
        
        // Menyimpan riwayat setiap menu yang dibeli
        String sqlDetail = "INSERT INTO tb_detail_transaksi (id_transaksi, id_menu, qty, subtotal) VALUES ('" + idTransaksiBaru + "', '" + idMenu + "', '" + qty + "', '" + subtotal + "')";
        Statement stDetail = conn.createStatement();
        stDetail.executeUpdate(sqlDetail);
        
        // Mengurangi stok di tb_menu secara otomatis!
        String sqlUpdateStok = "UPDATE tb_menu SET stok = stok - " + qty + " WHERE id_menu = '" + idMenu + "'";
        Statement stStok = conn.createStatement();
        stStok.executeUpdate(sqlUpdateStok);
    }
    
    JOptionPane.showMessageDialog(null, "Transaksi Berhasil! Kembalian: Rp. " + jTextField4.getText());
    
    // 4. Reset Form untuk pelanggan berikutnya
    modelKeranjang.setRowCount(0); // Kosongkan tabel keranjang
    grandTotal = 0;
    jLabelTotal.setText("Rp. 0");
    jTextField3.setText("");
    jTextField4.setText("");
    
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error Transaksi: " + e.getMessage());
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        try {
    // Mengambil total bayar dan uang yang diketik
    int total = grandTotal;
    int bayar = Integer.parseInt(jTextField3.getText());
    
    // Menghitung kembalian
    int kembali = bayar - total;
    
    // Menampilkan ke kolom Kembalian (jTextField4)
    jTextField4.setText(String.valueOf(kembali));
    jTextField4.setEditable(false); // Kunci kolom kembalian agar tidak bisa diedit
    
} catch (Exception e) {
    // Jika inputan uang tunai dihapus sampai kosong, kembalian ikut kosong
    jTextField4.setText("");
}
    }//GEN-LAST:event_jTextField3KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
